---
# Install docker-eingine
- name: "Add docker-engine apt key"
  apt_key:
    data: "{{ lookup('file', 'docker.asc') }}"
- name: "Add apt repository of docker-engine"
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_lsb.codename }} main"
- name: "Install docker-engine"
  apt: name=docker-engine
