---
# tasks file for ansible-role-docker
- name: "Install apt-transport-https,ca-certificates,curl"
  apt: name=apt-transport-https,ca-certificates,curl
- name: "Install software-properties-common"
  apt: name=software-properties-common
  when: ( ansible_lsb.codename == "jessie" or ansible_lsb.codename == "stretch" )

- name: "Install docker-ce"
  include: "docker-ce.yml"
  when: docker_ce_channel is defined and docker_ce_channel is not none

- name: "Install docker-engine"
  include: "docker-engine.yml"
  when: docker_ce_channel is not defined or docker_ce_channel is none

- name: "Read daemon.json"
  shell: |
    cat /etc/docker/daemon.json || echo '{}'
  register: result
  changed_when: no
- set_fact: docker_daemon_json="{{ result.stdout | from_json }}"
- name: "/etc/docker/daemon.json"
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0400
  when: "docker_daemon_json != docker_daemon_json|combine(docker_daemon_config)"
  notify: restart docker
